#ifndef EXPORT_H
#define EXPORT_H


#ifdef _BUILDING_ARMOR_CONFIGURATOR_
    #define ARMOR_DLL_EXPORT       QX_DLL_EXPORT_HELPER
    #define ARMOR_QX_REGISTER_HPP  QX_REGISTER_HPP_EXPORT_DLL
    #define ARMOR_QX_REGISTER_CPP  QX_REGISTER_CPP_EXPORT_DLL
#else // ! _BUILDING_ARMOR_CONFIGURATOR_
    #define ARMOR_DLL_EXPORT       QX_DLL_IMPORT_HELPER
    #define ARMOR_QX_REGISTER_HPP  QX_REGISTER_HPP_IMPORT_DLL
    #define ARMOR_QX_REGISTER_CPP  QX_REGISTER_CPP_IMPORT_DLL
#endif // _BUILDING_ARMOR_CONFIGURATOR_


#endif // EXPORT_H
